name: what3words
description: >-
  A Dart library to use the what3words v3 API. This library can either be used in native Dart or Flutter applications
version: 3.1.0
homepage: https://github.com/what3words/w3w-dart-wrapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 chopper: ^6.1.4
 os_detect: ^2.0.1

dev_dependencies:
  chopper_generator: ^6.0.2
  pedantic: ^1.11.0
  test: ^1.16.8
